let expected state =
  match state with
  | 0 -> ["\"state\"";]
  | 1 -> ["\"integer\"";]
  | 2 -> ["\":\"";]
  | 3 -> ["\"new line\"";]
  | 4 -> ["\"accept\"";"\"on\"";"\"production\"";"\"reduce\"";"\"shift\"";"\"state\"";"\"to\"";"\"nonterminal\"";]
  | 13 -> ["\"new line\"";]
  | 15 -> ["\"accept\"";"\"on\"";"\"production\"";"\"reduce\"";"\"shift\"";"\"state\"";"\"to\"";"\"nonterminal\"";]
  | 16 -> ["\"(\"";]
  | 17 -> ["\"accept\"";"\"on\"";"\"production\"";"\"reduce\"";"\"shift\"";"\"state\"";"\"to\"";"\"nonterminal\"";"\"terminal\"";]
  | 20 -> ["\",\"";"\")\"";]
  | 22 -> ["\"accept\"";"\"on\"";"\"production\"";"\"reduce\"";"\"shift\"";"\"state\"";"\"to\"";"\"nonterminal\"";"\"terminal\"";]
  | 25 -> ["\"'\"";]
  | 28 -> ["\"->\"";]
  | 29 -> ["\"accept\"";"\"on\"";"\"production\"";"\"reduce\"";"\"shift\"";"\"state\"";"\"to\"";"\"#\"";"\"[\"";"\"nonterminal\"";"\".\"";"\"terminal\"";]
  | 32 -> ["\"accept\"";"\"on\"";"\"production\"";"\"reduce\"";"\"shift\"";"\"state\"";"\"to\"";"\"#\"";"\"[\"";"\"nonterminal\"";"\".\"";"\"terminal\"";]
  | 34 -> ["\"]\"";]
  | 36 -> ["\"accept\"";"\"on\"";"\"production\"";"\"reduce\"";"\"shift\"";"\"state\"";"\"to\"";"\"#\"";"\"[\"";"\"nonterminal\"";"\".\"";"\"terminal\"";]
  | 41 -> ["\"new line\"";]
  | 43 -> ["\"--\"";]
  | 44 -> ["\"on\"";]
  | 45 -> ["\"accept\"";"\"on\"";"\"production\"";"\"reduce\"";"\"shift\"";"\"state\"";"\"to\"";"\"#\"";"\"nonterminal\"";"\".\"";"\"terminal\"";]
  | 46 -> ["\"accept\"";"\"reduce\"";"\"shift\"";]
  | 47 -> ["\"to\"";]
  | 48 -> ["\"state\"";]
  | 49 -> ["\"integer\"";]
  | 50 -> ["\"new line\"";]
  | 52 -> ["\"production\"";]
  | 53 -> ["\"accept\"";"\"on\"";"\"production\"";"\"reduce\"";"\"shift\"";"\"state\"";"\"to\"";"\"nonterminal\"";]
  | 55 -> ["\"accept\"";"\"on\"";"\"production\"";"\"reduce\"";"\"shift\"";"\"state\"";"\"to\"";"\"nonterminal\"";]
  | 56 -> ["\"new line\"";]
  | 60 -> ["\"--\"";]
  | 62 -> ["\"state\"";]
  | 65 -> ["\"end of input\"";]
  | _ -> []
